version = 1

[envs.main]
channels = ["conda-forge"]

[envs.main.dependencies]
dask = "*"
ipython = "*"
jupyter = "*"
matplotlib = "*"
napari = "*"
numba = "*"
numpy = "*"
opencv = "*"
pandas = "*"
scikit-image = "*"
scikit-learn = "*"
seaborn = "*"
xarray = "*"

[envs.main.exposed]
jupyter = "jupyter"
ipython = "ipython"
napari = "napari"
