version = 1

[envs.main]
channels = ["conda-forge"]
dependencies = {
    dask = "*",
    ipython = "*",
    jupyter = "*",
    matplotlib = "*",
    napari = "*",
    numpy = "*",
    opencv = "*",
    pandas = "*",
    scikit-image = "*",
    scikit-learn = "*",
    seaborn = "*",
    xarray = "*",
}
exposed = {
    jupyter = "jupyter",
    ipython = "ipython",
    napari = "napari",
}
